In [1]:
%load_ext autoreload

%autoreload 2

import pickle

import numpy as np
import scipy.optimize

import threebody
import kepler


In [2]:
p = {'ppn_mode': 'heavysimple', 
     'shapiro': True, 
     'asini_i': 1.2175250267506728307, 
     'eps2_i': -9.1426736677540146229e-05, 
     'delta_lan': 4.4761213359685543749e-06, 
     'eps2_o': -0.0034632643340192177883, 
     'q_i': 0.13741473358758702261, 
     'general': True, 
     'dgamma': 3.1613419576212658719e-05, 
     'tasc_i': 0.40771655919836252534, 
     'acosi_o': 91.370388640747020811, 
     'acosi_i': 1.489573103261630733, 
     'special': True, 
     'tasc_o': 313.93502573359101213, 
     'eps1_o': 0.03518590691922095078, 
     'eps1_i': 0.00068843880563762498484, 
     'tol': 1e-16, 
     'use_quad': False, 
     'pb_i': 1.6293926665087130991, 
     'matrix_mode': 0, 
     'delta': -1.3172471727351514064e-06, 
     'asini_o': 74.672617583808625193, 
     'dbeta': -0.00050144218332275676054, 
     'pb_o': 327.25675133252292962, 
     'kopeikin': False}

In [3]:
threebody.compute_orbit(p, [10,20])

0.0353559364969 -7.62578151174
0.000694483143991 -3.27366668269


{'initial_values': array([  1.13357330e+02,   2.15574413e+01,   1.76181043e+01,
          6.75801205e+00,   1.69200657e+00,   1.38279310e+00,
          1.43576049e+00,   1.13355112e+02,   3.38954835e+01,
          2.77027891e+01,  -5.46057065e+01,   1.68973756e+00,
          1.38093849e+00,   1.97294646e-01,  -4.51914058e+02,
         -9.18842909e+01,  -7.50942583e+01,   2.61338844e+00,
         -6.74433212e+00,  -5.51180823e+00,   4.09631719e-01,
          0.00000000e+00]),
 'n_evaluations': 16467,
 'parameter_dict': {'acosi_i': 1.4895731032616308,
  'acosi_o': 91.37038864074702,
  'asini_i': 1.2175250267506728,
  'asini_o': 74.67261758380863,
  'dbeta': -0.0005014421833227568,
  'delta': -1.3172471727351514e-06,
  'delta_lan': 4.4761213359685544e-06,
  'dgamma': 3.161341957621266e-05,
  'eps1_i': 0.000688438805637625,
  'eps1_o': 0.03518590691922095,
  'eps2_i': -9.142673667754015e-05,
  'eps2_o': -0.003463264334019218,
  'general': True,
  'kopeikin': False,
  'matrix_mode': 0,
  'p

In [4]:
ics = [1.2175250267506728307, 1.6293926665087130991, 0.00068843880563762498484, -9.1426736677540146229e-05, 0.40771655919836252534, 1.489573103261630733, 0.13741473358758702261, 74.672617583808625193, 327.25675133252292962, 0.03518590691922095078, -0.0034632643340192177883, 313.93502573359101213, 91.370388640747020811, 4.4761213359685543749e-06, 0, 
       np.array([ 0.,  0.,  0.]), np.array([ 0.,  0.,  0.]), 0]


In [5]:
kepler.kepler_three_body_measurable(*ics)

0.0353559364969 -7.62578151174
0.000694483143991 -3.27366668269


(array([  1.13357330e+02,   2.15574413e+01,   1.76181043e+01,
          6.75801205e+00,   1.69200657e+00,   1.38279310e+00,
          1.43576049e+00,   1.13355112e+02,   3.38954835e+01,
          2.77027891e+01,  -5.46057065e+01,   1.68973756e+00,
          1.38093849e+00,   1.97294646e-01,  -4.51914058e+02,
         -9.18842909e+01,  -7.50942583e+01,   2.61338844e+00,
         -6.74433212e+00,  -5.51180823e+00,   4.09631719e-01]),
 array([[  8.81232705e-05,   1.85506321e+00,   1.00047221e+00,
          -1.00418522e+00,  -7.41354827e+00,   1.07813844e-04,
          -1.05304684e-13,   6.07894848e-01,  -6.28851141e-01,
          -1.55235518e+02,  -9.93453575e+00,   6.55536224e-01,
           7.43829193e-01,   2.30480399e+01,   2.15574413e+01,
           1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           6.75801205e+00],
        [ -6.47050744e-17,   6.85935785e-05,  -1.65816712e+00,
           1.68528868e-01,  -2.7

In [6]:
ics = pickle.load(open("bogus-ics.pickle"))

In [11]:
kepler.kepler_three_body_measurable(*ics)

(array([  1.13378357e+02,   2.15645188e+01,   1.76181024e+01,
          6.75907519e+00,   1.69252930e+00,   1.38279267e+00,
          1.43593607e+00,   1.13376144e+02,   3.39044570e+01,
          2.77016361e+01,  -5.46074817e+01,   1.69026417e+00,
          1.38094172e+00,   1.97344414e-01,  -4.51924969e+02,
         -9.18992702e+01,  -7.50821365e+01,   2.61347228e+00,
         -6.74532945e+00,  -5.51091897e+00,   4.09754348e-01]),
 array([[  8.79555628e-05,   1.85535867e+00,   1.00033732e+00,
          -1.00404591e+00,  -7.41473822e+00,   1.07637486e-04,
          -1.27522137e-14,   6.07781184e-01,  -6.28972834e-01,
          -1.55267546e+02,  -9.93345176e+00,   6.55663029e-01,
           7.43920211e-01,   2.30555167e+01,   2.15645188e+01,
           1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           6.75907519e+00],
        [ -7.55921069e-16,   6.84842409e-05,  -1.65857035e+00,
           1.68531663e-01,  -2.7

In [12]:
kepler.eccentric_from_mean(0.0353561155606, -7.62575615004)

(-7.6604522220568061, [-0.98805011813107613, 1.0068463697961494])